version: '3.8'

services:
  db:
    image: postgres:15
    container_name: employer-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employer_portal
    ports:
      - "5433:5432"

  api:
    build: .
    container_name: employer-api
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: employer_portal
